name: ht_data_repository
description: A generic repository that acts as an abstraction layer over an HtDataClient.
repository: https://github.com/headlines-toolkit/ht-data-repository
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  ht_data_client:
    git:
      url: https://github.com/headlines-toolkit/ht-data-client.git
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git
  
dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^9.0.0